'use client';

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Trash2 } from "lucide-react";
import { toast } from "sonner";
import { deleteUnpaidInvoice } from "@/app/admin/actions/invoices";
import ConfirmDialog from "@/components/dashboard/ConfirmDialog";

// Removes an invoice that was made by mistake, such as one entered twice, after
// a confirmation. Shown only when nothing has been paid against it.
export default function DeleteUnpaidInvoiceButton({ paymentId, label, autoGenerated }: { paymentId: string; label: string; autoGenerated: boolean }) {
    const router = useRouter();
    const [asking, setAsking] = useState(false);
    const [busy, setBusy] = useState(false);

    const remove = async () => {
        setBusy(true);
        const result = await deleteUnpaidInvoice(paymentId);
        setBusy(false);
        setAsking(false);

        if (!result.success) {
            toast.error(result.error ?? "Could not delete this invoice.");
            return;
        }

        toast.success("Invoice deleted");
        router.refresh();
    };

    return (
        <>
            <button
                type="button"
                onClick={() => setAsking(true)}
                className="inline-flex items-center gap-1.5 rounded-lg border border-red-400/30 bg-red-500/10 px-3 py-1.5 text-xs font-bold text-red-300 transition hover:bg-red-500/20"
            >
                <Trash2 className="h-3.5 w-3.5" />
                Delete this invoice
            </button>
            <ConfirmDialog open={asking} title="Delete this invoice?" confirmLabel="Yes, delete it" tone="danger" busy={busy} onConfirm={remove} onCancel={() => setAsking(false)}>
                <p>
                    {label} will be removed for good. Use this for an invoice made by mistake, such as one entered twice. Nothing has been paid on it.
                    {autoGenerated ? " It was made automatically, so the next monthly run may create it again if it is still due." : ""}
                </p>
            </ConfirmDialog>
        </>
    );
}
